apiVersion: 1
datasources:
  - name: Rex
    type: rex-otel-datasource
    uid: rex-otel
    access: proxy
    url: http://127.0.0.1:9470
    isDefault: true
    editable: false
    jsonData:
      catalogPath: /v1/catalog
      queryPath: /v1/metrics/query
