from __future__ import annotations

from typing import Protocol

from app.logging.models import DecisionRecord


class DecisionRepository(Protocol):
    async def save(self, record: DecisionRecord) -> None: ...
    async def get_recent(self, limit: int) -> list[DecisionRecord]: ...
    async def count(self) -> int: ...
    async def get_embeddings(self) -> list[tuple[str, bytes]]: ...
    async def get_rule_votes(self) -> dict[str, dict[str, float]]: ...
    async def clear_all(self) -> None: ...
